name: Git flags
description: Sets git-clone and git-fetch flags
author: https://github.com/Hivebrite
requirements: ['git']
configuration:
  properties:
    clone:
      type: string
    fetch:
      type: string
  required: []
